name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.x"

      - name: Check Formatting
        run: deno task fmt-check

      - name: Run Linter
        run: deno task lint
      
      - name: Type Check
        run: deno task check
      
      - name: Run Tests
        run: deno task test